name: Deploy to Hosting via FTP

on:
  push:
    branches:
      - main # Akan berjalan setiap kali ada push ke branch main

jobs:
  deploy:
    name: Deploy Theme to Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "."
          remoteDir: "."
          options: "--exclude .git/ --exclude .github/ --exclude README.md"
